#!/bin/bash

VERSION=${MAJOR_VERSION:-0.1.}
IMAGE_VERSION=$VERSION$GO_PIPELINE_COUNTER-${GO_REVISION_PARSER_WEB:0:12}
IMAGE_NAME="parser-web"

DOCKER_REGISTRY_URL=$DOCKER_REGISTRY_URL


IMAGE_FULL_NAME=$DOCKER_REGISTRY_URL/test/$IMAGE_NAME:$IMAGE_VERSION

# build and push
docker build -t $IMAGE_NAME:$IMAGE_VERSION .
docker tag $IMAGE_NAME:$IMAGE_VERSION $IMAGE_FULL_NAME
docker push $IMAGE_FULL_NAME

# remove
docker rmi $IMAGE_NAME:$IMAGE_VERSION
docker rmi $IMAGE_FULL_NAME
